spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
  datasource:
    url:  jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/changelog/changelog.xml